services:
  frontend:
    build:
      context: .
      target: frontend-builder
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
      - HOST=0.0.0.0
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_ENV=production
    depends_on:
      - backend
    command: npm run start
    working_dir: /app/frontend

  backend:
    build:
      context: .
      target: backend-builder
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_PORT=5000
    command: python -m flask run --host=0.0.0.0 --port=5000
    working_dir: /app/backend 